(defun test (x)
    (format t "~a => ~s~%" x (eval (read-from-string x))))

(defvar num 1)
(defvar lis '(1 2 3))
(test "`(foo num)")
(test "`(foo ,num)")
(test "`(,num foo)")
(test "`(foo ,lis)")
(test "`(,lis foo)")
(test "`(foo ,@lis)")
(test "`(,@lis foo)")
(test "`(foo ,lis num)")
(test "`(foo ,@lis num)")
(test "`(,@lis foo num)")
(test "`(,@lis foo ,num)")
(test "`(foo ,lis ,num)")
(test "`(foo ,@lis ,num)")
(test "`(foo ,lis ,@num)")
